title: VvE Parkresidentie Dronten
description: Vereniging van Eigenaren Parkresidentie Dronten

url: http://vve.parkresidentiedronten.nl
baseurl: ""
paginate_path: "artikel/page:num/"
permalink: artikel/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Start
    url: /index.html
  - title: Documenten
    url: /documenten
  - title: Historie
    url: /historie
  - title: Over
    url: /over
  - title: Contact
    url: /contact

